### ISSUE TITLE
Error when hitting /!/zipper/create

### ISSUE THREAD

**Issue by taylorcammack** [aerni/statamic-zipper#1]
![Screen Shot 2021-10-25 at 3 34 38 PM](https://user-images.githubusercontent.com/2514935/138766818-8b070bdd-2ba4-427e-9118-63a547682b5e.png)

Any ideas?

**Comment by aerni** [comment]
I'm going to need more information about your setup. But this looks like an issue with your local server rather than an issue with the addon. Have you tried it without the live server? Like `http://mysite.test/!/zipper/...`?

**Comment by taylorcammack** [comment]
Yep, had tried that as well, with the same result. I'm using Valet. Nothing particular exotic about the set-up. Any gotchas that you can think of?

**Comment by aerni** [comment]
What version of the addon, Statamic and PHP are you on?

**Comment by taylorcammack** [comment]
- Statamic 3.2.18 Pro
- Laravel 8.65.0
- PHP 7.4.25
- aerni/zipper 1.2.0

**Comment by aerni** [comment]
Fixed the issue with release v1.3.0.

**Comment by taylorcammack** [comment]
Thank you! 🙏
