### ISSUE TITLE
500 server error when trying to zip

### ISSUE THREAD

**Issue by ghost** [aerni/statamic-zipper#5]
I am calling in zipper as follows

```   <a href="{{ zip:artwork }}">test</a>```

which cause a 500 server error.

PHP 8, laravel 9, statamic 3

**Comment by aerni** [comment]
What does your error log say?

**Comment by ghost** [comment]
Hello thanks for the quick reply

Here is the logged error:
```
[2022-05-19 01:54:18] local.ERROR: Call to a member function raw() on null {"userId":"54924891-a274-4d26-a470-31a14707808f","exception":"[object] (Error(code: 0): Call to a member function raw() on null at /var/www/laravel/vendor/aerni/zipper/src/ZipperTags.php:54)
```

**Comment by aerni** [comment]
Ok, it seems like the `artwork` variable doesn't actually contain anything? You can check if the variable exists by dumping it on the frontend with `{{ artwork | dump }}`.

**Comment by ghost** [comment]
That doesn't make sense, considering i am calling in {{ artwork }} in the same antlers file to pull in the album artwork for a release and display it. Do i need to include the sub-field name? like {{ artwork:upload_files }} ?

**Comment by aerni** [comment]
I suppose `artwork` is an asset fieldtype? I'm going to need some more information from you so I can reproduce this issue. Also, I'm working on a complete refactor right now. So this problem might be resolved anyways.

**Comment by ghost** [comment]
Yes, artwork is an asset and links to a specific assets folder for album artwork, and that same artwork has no other issues displaying on the site when i call it in via <img> tags.

The artwork  was just a test to see if I could get zipper working, as the actual goal is to have it zip up the Audio files on a release which are individual 'tracks' in a collection but each of those tracks has its own file uploaded. That seemed a bit more difficult to get working so I just wanted to get something simple working by zipping a single image

**Comment by ghost** [comment]
Also thanks for the update and letting me know its being re-factored. I can probably implement a workaround until it has a fix available.

This is an unrelated thread but I was also having issues with snipcart(which i purchased) in this same instance, where it would not let me create a new entry for product and gave me a 500 error as well. I am going to give an update in your snipcart repo once i check the logs

**Comment by ghost** [comment]
> Ok, it seems like the `artwork` variable doesn't actually contain anything? You can check if the variable exists by dumping it on the frontend with `{{ artwork | dump }}`.

Okay i am extremely sorry for the confusion
i checked my files again and I was missing a quotation mark -_-
i can get the artwork to zip now. sorry again

**Comment by aerni** [comment]
Haha, no worries. Been there myself ;-)
